### ISSUE TITLE
Remove section of the Process on Workshop and Symposia

### ISSUE THREAD

**Issue by frivoal** [w3c/process#419]
While Workshops and Symposia, (as well as other types of events organized by w3c such as [meetups](https://www.w3.org/2018/10/Meetup/), [summits](https://www.w3.org/publishing/events/summit2017.html), [forums](http://www.webexecutiveforum.com/)…) are useful, the [section of the process](https://w3c.github.io/w3process/#GAEvents) that defines them hardly accomplishes anything.

It starts by saying what events called "Workshops" and "Symposia" are "usually" for, so it's not even binding about what they're about. Then the text has a few MAYs, no SHOULD, and the only MUSTs it has is about how many weeks in advance each type of event needs to be announced. Working around that restriction is both trivial (call your Symposium a Summit, and you're not longer bound to announce it 8+ weeks in advance) and ill advised (organizing events without giving people time to sign up is self defeating).

I think we could remove the whole section from the Process without losing anything. Instead, a more comprehensive article (on /Guide?) giving best practices for organizing various kinds of public or semi-public events would likely do a better job at establishing how such events are meant to be organized, when do pick which kind, etc.

**Comment by jeffjaffe** [comment]
As an fyi, the Team often delays Workshops because of the MUST requirement.  While there are workarounds, often stakeholders really want a Workshop and the process language is effective in preventing an ill-advised rush to a workshop.

**Comment by nigelmegitt** [comment]
+1 to keeping the requirement that prevents small groups from organising an "official" event of some kind with inadequate notice for general attendance, and also +1 to stripping out unnecessary verbiage that can go elsewhere.

**Comment by frivoal** [comment]
This minimum delay requirement could still be documented as a guideline/best practice / general expectation in the /Guide article.

If we do want to keep it in the Process, we could massage [section 3.2](https://w3c.github.io/w3process/#GeneralMeetings) to cover for Workshops as well.

**Comment by nigelmegitt** [comment]
> guideline/best practice / general expectation

If we were in the unfortunate situation of a small group trying to pressgang others into something without adequate notice or review period, by holding a meeting at short notice, I don't think this approach would be strong enough to support anyone saying "no, you can't do this", because the response would be "that's only a guideline".

**Comment by dwsinger** [comment]
This is a short 'leaf' section that doesn't complicate the process, so I am easy, except that I think we should try to keep requirements in the process document, and the paragraph with the requirements might be rather lonely without the introductory paragraphs before it.

**Comment by frivoal** [comment]
I remain of the opinion that that section of the Process is ineffective. If its value comes from requiring a delay before a meeting can be held, then we should have a definition of what type of meeting this applies to, and it doesn't even have that: the minimum time applies to Workshops and Symposia, but nothing defines what those are. It is trivially to work around that requirement, such as by doing the exact same thing and calling them Seminars and Summits.

**Comment by frivoal** [comment]
Updated proposal:
* Add a one liner to [Meeting Scheduling and Announcements](https://www.w3.org/2023/Process-20231103/#meeting-schedules) indicating that the minimum notice periods for F2F meetings apply not just to Group meetings, but to all official W3C meetings open to Members and/or the public, including Workshops.

* /Guide already has a definition of Workshops. Use that as the main reference for what Workshops are for.

* Delete section [Workshops and Symposia](https://www.w3.org/2023/Process-20231103/#GAEvents) from the Process

**Comment by Octocat-dev** [comment]
[![Main Checks](https://github.com/digitalbazaar/forge/actions/workflows/main.yml/badge.svg)](https://github.com/digitalbazaar/forge/actions/workflows/main.yml)
