### ISSUE TITLE
Simplify member submissions

### ISSUE THREAD

**Issue by frivoal** [w3c/process#421]
Member Submissions are used a few times per year ([7 times since 2015](https://www.w3.org/Submission/), so the membership finds some value in them. But [the section that defines them](https://w3c.github.io/w3process/#Submission) is quite long at complicated. Clocking it at a little over four A4 pages in a pdf rendering, it might not need quite that much complexity. For comparison, this is a little longer than the sum of the sections covering charters (including what goes in there, AC reviews of charters, the process for re-chartering, group closures, charter extensions…), even though it's not nearly as important.

Although some editorial massaging may be possible, I suspect that to significantly simplify and shrink that section, we need to actually change how Member Submissions work. To do that well, I think we need to think about what they're trying to accomplish.

The way I understand them, they allow a Member (or a group of Members) to submit material to the W3C community:
* to be hosted on the W3C website, with the usual archival and availability guarantees, for ease of reference
* with clarity about whether patent commitments will be offered should that proposal make its way to the REC track
* without obtaining the consensus of a WG prior to submitting it
* possibly even before a related WG even exists

Along the way, it gets assessed by the Team / Director, who may reject it "for a variety of reasons", only some of which are listed. I believe that later part is much less useful, as it is arbitrary and ill defined, and having the Director as gate keeper of good for / harmful to the Web feels quite out of place nowadays. If we need any review at all, having the TAG or/and HR groups provide it would seem more relevant, and maybe it could be provided after publication of the submission, rather than blocking it.

I think that if we redesign the whole thing based on the simplified goals above, maybe with some  optional TAG/HR review, we could achieve something which would at the same time be much simpler/shorter in the Process, simpler in practice, and more in line with modern practices.

**Comment by jeffjaffe** [comment]
@frivoal I agree with the general thrust.   The team is not looking for a reduction of its workload here, and I often hear from HR groups that they are overloaded, so I'm not convinced that there is value add moving this to TAG/HR groups.

**Comment by nigelmegitt** [comment]
+1 to explaining more clearly what aspects of review will happen to Member Submissions and the classes of reason for rejection.

-1 to changing the process _only_ for the sake of reducing Process document length.

+1 to making it easier to understand why submitting a MS might be a useful thing to do, for example to initiate work in a WG to create a W3C Recommendation.

The submission process itself has 2 steps. I'd argue that's simple enough already.

**Comment by frivoal** [comment]
In 3 years since I opened this issue, the Member submission process has been used twice. I remain under the impression that this process has some value, but that it doesn't warrant all the rules we have about it.

> -1 to changing the process only for the sake of reducing Process document length.

To me, it's not about word count per se, it's about complexity. Both in terms of how it interact with other things, and of how much people need to be aware of to make good use of this process.

For instance, because Member Submissions can be rejected, we need an appeal process for when they are. That involved some thinking about how to integrate it with the Council, taking into account the fact that the confidentiality of that appeal has to be different from the confidentiality of other Councils (and remembering that every time we make edits about the Council in general).

As far as I can tell, Member Submission can be used to solve https://github.com/w3c/w3process/issues/460, and it's their primary or only value nowadays. I would be tempted to strip off everything that isn't in support of that goal.
