### ISSUE TITLE
Clarify deadline for nominations

### ISSUE THREAD

**Issue by fantasai** [w3c/process#464]
To help the problem of "incomplete" nominations go away, let's clarify the Process to say as long as the AC rep has named a nominee by the deadline, the collection of additional information can continue after the nomination deadline.

**Comment by frivoal** [comment]
It depends what is meant by incomplete. The Process lists (in the 4th paragraph of https://w3c.github.io/w3process/#AB-TAG-elections) a number of things that are necessary to know whether a nomination is valid. Until they are all collected, we cannot know whether the nomination will stand or whether it will be ruled out, and if we cannot know how many are valid, we cannot know if the nomination period needs to be extended or not, whether the nominees win without an election, or whether we need to hold an election. I think the following points can be collected after the deadline, but the rest must be ready before the deadline (and nominations should be considered invalid if it is not):
* > The nomination form must ask for the nominee’s primary affiliation, and this will be reported on the ballot.
* > Each nomination should include a few informative paragraphs about the nominee.
* found by indirection via [information required for a Member representative in a Working Group](https://w3c.github.io/w3process/#member-rep-info):
    > A statement that the Member will provide the necessary financial support for participation (e.g., for travel, telephone calls, and conferences). 
* found by indirection via [information required for an Invited Expert in a Working Group](https://w3c.github.io/w3process/#inv-expert-info):
    >  provide a statement of who will provide the necessary financial support for the individual’s participation (e.g., for travel, telephone calls, and conferences)

    and
    > if the individual’s employer (including a self-employed individual) or the organization the individual represents is not a W3C Member, indicate whether that organization intends to join W3C. If the organization does not intend to join W3C, indicate reasons the individual is aware of for this choice.

**Comment by dwsinger** [comment]
I think that the team is graceful in allowing small mistakes and omissions in nominations not to cause them to be discarded. Do we need to encode this, or is this practice good enough? (I think it is good enough, and would close/no-action).

**Comment by dwsinger** [comment]
We'd like suggestions for small textual changes to clarify what the team can fix after the deadline (not including the deadline itself).

**Comment by cklim4405** [comment]
Use

**Comment by cklim4405** [comment]
Use update

**Comment by cklim4405** [comment]
Samsung

**Comment by frivoal** [comment]
As noted in https://lists.w3.org/Archives/Member/w3c-ac-forum/2024OctDec/0080.html, the AB did resolve on:
> The AB believes nomination periods should not be extended to collect more candidates unless the nomination period expires with insufficient candidates to meet the minimum number of seats. If there are insufficient candidates to meet the minimum number of seats, a new Call for nominations mail should be issued as per https://www.w3.org/policies/process/drafts/#AB-TAG-elections, and the election is delayed until the end of that new call for nominations.

**Comment by frivoal** [comment]
PR at https://github.com/w3c/process/pull/950
