### ISSUE TITLE
Who can initiate and prepare a Charter?

### ISSUE THREAD

**Issue by dwsinger** [w3c/process#560]
Though it's clear in the process that the team has certain obligations, e.g. to send out charters for AC approval, it's not clear whether they are the only place where charters can be prepared, or whether they have discretion on whether to send charters for approval. Could a charter be prepared by other than the team, and sent to the team to be sent to the AC for approval without their ability to delay or stop such vote or adoption?

**Comment by jeffjaffe** [comment]
Today before a team sends a charter for AC review, it goes through various reviews including W3M review (to assess maturity, feasibility, known problems, team resources assigned, etc.) as well as horizontal reviews (to assess whether there are problems in horizontal areas).  If we broaden the preparation of charters beyond the team we should be thoughtful about the types of reviews that might be desirable before sending for AC review.

**Comment by dwsinger** [comment]
@jeffjaffe I think the team undoubtedly has the responsibility to review and comment, and solicit review and comment; I don't question that. But if the team felt that something wasn't important, or even that it was the wrong WG to form, could they impede or stop if a group of proponents in the membership heard their comments and still wanted to proceed?

**Comment by frivoal** [comment]
If there is a clear mechanism for proposing that the Team moves a charter forward, so that when the Team disagrees, it must explicitly record a decision to reject (after having tried more conciliatory ways to resolve differences), then it's possible to raise an objection against the decision, and we have ways to deal with those.

What's problematic is if:
* it's not clear how to propose a charter
* once a charter is proposed, it is possible that Team  neither explicitly rejects it in a way that can be appealed, nor moves it forward

I am unsure that the second point is an issue in practice, but it would build trust in the process for the membership to be able to know for sure that it cannot happen.

For the first point, I think it is an issue. If you want to create a CG, there's a form you can fill to kick-start the process. For A WG or an IG, you need to be a bit more of an insider and to know who to talk to. Having a formal and easy-to-identify entry-point seems very desirable.

What I don't think is an issue is a precise set of strict criteria a charter must fulfill to be acceptable. If we have the above, guidelines are likely enough at that stage: the Team can review and help make it better based on their experience and understanding, and if the Team's judgement (in either direction) is in conflict with member expectations, Formal Objections can deal with that.

**Comment by dwsinger** [comment]
> If there is a clear mechanism for proposing that the Team moves a charter forward, so that when the Team disagrees, it must explicitly record a decision to reject (after having tried more conciliatory ways to resolve differences), then it's possible to raise an objection against the decision, and we have ways to deal with those.
> 
> What's problematic is if:
> 
> * it's not clear how to propose a charter
> * once a charter is proposed, it is possible that Team  neither explicitly rejects it in a way that can be appealed, nor moves it forward
> 
> I am unsure that the second point is an issue in practice, but it would build trust in the process for the membership to be able to know for sure that it cannot happen.
> 
> For the first point, I think it is an issue. If you want to create a CG, there's a form you can fill to kick-start the process. For A WG or an IG, you need to be a bit more of an insider and to know who to talk to. Having a formal and easy-to-identify entry-point seems very desirable.
> 
> What I don't think is an issue is a precise set of strict criteria a charter must fulfill to be acceptable. If we have the above, guidelines are likely enough at that stage: the Team can review and help make it better based on their experience and understanding, and if the Team's judgement (in either direction) is in conflict with member expectations, Formal Objections can deal with that.

I think it's a perception: that Charters that the team likes move along, and other charters can languish. I don't think the perception is healthy, whatever the reality.

**Comment by plehegar** [comment]
Note that our [charter development process](https://www.w3.org/Guide/process/charter.html) is documented in the Guide. It does not however formally establish how to work with the team to kick start the process. Nowadays, we keep track of those things in our [incubation pipeline](https://github.com/w3c/strategy/projects/2) so I can easily imagine encouraging to raise issues there for example. cc @wseltzer 

As an example, among charters prepared by Members and not sent to the AC for formal review is the [Decentralized IG](https://github.com/w3c/strategy/issues/231). I believe we're still waiting on a conclusion from the feedback, including the level of support within our Members.

If we wanted to improve the Process, as Florian suggests, I can imagine that the team ought to follow up on advance notices. Such as linking back to the advance notice when we start a formal review, or sending a dedicated message to provide a status update (with some duration expectation?).

**Comment by plehegar** [comment]
one more thing: the  [charter development process](https://www.w3.org/Guide/process/charter.html) is linked from the Process but as part of the horizontal reviews on charters, not as part of charter creation. If we improve the Guide, we should also improve the linkage from the Process.

**Comment by mnot** [comment]
The language in both the guide and the process gives the overwhelming impression that only the Team can actually create a charter:

> W3C creates a charter based on interest from the Members and Team. The Team must notify the Advisory Committee when a charter for a new Working Group or Interest Group is in development. This is intended to raise awareness, even if no formal proposal is yet available. Advisory Committee representatives may provide feedback on the Advisory Committee discussion list.
>
> W3C may begin work on a Working Group or Interest Group charter at any time.

> First, W3M chooses a Team Contact to manage the group creation process.

> The Team Contact works with the Strategy Lead to draft a provisional charter. See the Charter template and W3C Process Document for the list of charter requirements. The Team Contact may wish to share drafts of the provisional charter with a candidate Chair (if one exists), a relevant interest group or interested community of W3C members prior to Member review.

**Comment by wseltzer** [comment]
Thanks for those pointers @mnot and @plehegar . Since our practice includes much more community involvement, I'll draft some PRs to make the Guide more inviting.

**Comment by wseltzer** [comment]
PR to update /Guide with reference to community charter development.

**Comment by fantasai** [comment]
Minutes from the AC session on chartering earlier today: https://www.w3.org/2023/05/10-ac-brk-strategy-minutes.html
