### ISSUE TITLE
Recommendation track diagram does not show Rec maintenance

### ISSUE THREAD

**Issue by svgeesus** [w3c/process#596]
In [The W3C Recommendation Track](https://www.w3.org/2021/Process-20211102/#rec-track) there is a nice diagram which clearly shows the steps from (FP)WD through CR with some CRD and then PR and Rec.

![image](https://user-images.githubusercontent.com/2506926/150006406-4fb854b6-ea73-41ec-9787-5974cfcebd12.png)

There is a single arrow to Rec, which from the diagram is clearly an end state  with no further options. This is false because:

- updated Rec with editorial changes
- updated Rec with candidate corrections
- updated Rec with candidate additions
- updated Rec with proposed corrections
- updated Rec with proposed additions
- updated Rec where the proposed changes have been folded in

are all possible.

To avoid clutter, I suggest a second diagram entitled "Rec maintenance" which shows these steps (and adds the option to go back to CR, or to go back to FPWD for a new version if the previous version did not allow additions.

**Comment by chaals** [comment]
I'm glad you think it's nice.

Feel free to take it and shake it into something like the second diagram you think we should have (I agree we should, but I'm waiting for someone else to make it).

**Comment by svgeesus** [comment]
Thanks, please feel free to close.
