### ISSUE TITLE
Should member submissions be removed from the Process?

### ISSUE THREAD

**Issue by frivoal** [w3c/process#648]
As suggested by @michaelchampion in https://github.com/w3c/w3process/issues/639#issuecomment-1255394173

@michaelchampion :
> Does the concept of a "member submission" still belong in the Process, considering the evolution of the patent policy, the near-universal use of "forkable" copyright licenses in web standards, and the use of community groups as the typical incubation mechanism? It would seem cleaner to just remove member submissions to the process than try to untangle the Director from yet another corner case.

@dwsinger :
> The [history](https://www.w3.org/Submission/) suggests that they remain an active tool.

@michaelchampion :
> Well sure, if you expose a lever, people will yank on it. Are they doing anything with that lever they couldn't do if it were removed? Is repairing the mechanism the lever controls worth the trouble, considering you could just remove the lever?

@jeffjaffe :
> As per the history that David cites, it has been useful particularly to get input from industry groups.

@michaelchampion :
> Again, what input are you getting via the submission process you couldn't get from normal participation in WGs,  IGs or CGs?
> 
> I know from personal experience the Member Submission process was abused in the past to get the appearance of W3's imprimatur on "input from industry groups" that had no broad industry support or prospects of getting into a Recommendation. I don't know of that happening in the last 10 years or so, but I don't see many submissions that had a real impact since the FIDO submission in 2015 either. 
> 
> This is a pretty minor nit in the Process so I don't really care what happens to this issue, but I am concerned that the Process is accreting ever more complexity to cover anachronistic corner cases.  Assuming W3C survives the LE transition and the AB can focus on process and community issues next year, cleaning up this sort of legacy cruft might be worth some attention.

@mnot:
> I tend to agree with Michael here - member submissions made sense pre-CG, much less so now.

@michaelchampion:
> I proposed resolving the issue of how to appeal member submission decisions by removing member submissions🤷
>
> If I have an issue with my appendix or gall bladder, my doctors won’t spend time trying to fix it, they will resolve the issue by removing the problematic organ.

@palemieux:
> @michaelchampion Say a group of folks that a not W3C members come up with a spec, and would like to continue the work in W3C, how would they get started?

@michaelchampion :
> Create a Community Group; have the CG publish the spec with an open copyright license and patent commitments from the contributors; build a community of users who have problems the spec solves, implementers who will support the standard in their products, tools, frameworks, etc.; then draft a charter for a new WG or discuss expanding the charter of an existing WG to put the “incubated”spec in scope.

@palemieux:
> Is there any way for the contribution, with the relevant patent commitments, to be directly accepted by a WG?

@michaelchampion:
> I don't see why not, but I haven't thought about this for a while. If someone writes a spec, joins a WG for which it is in scope thus making patent commitments to anything the WG takes to Rec, proposes it and the WG accepts it, I don't foresee any problems.
>
> Member submissions historically were for situations where there wasn't an existing WG with the spec in scope, and before there were CGs with a patent policy designed to cover such incubation scenarios.
> 
> To be clear, I don't have strong feelings on whether member submissions should be removed from the process. I'm just suggesting the Process CG convince themselves that member submissions are worth fixing to work in a director-free world as opposed to just removing them from the Process so this issue doesn't arise.

**Comment by palemieux** [comment]
As suggested by @michaelchampion, a member submission could be considered by a CG or WG no differently than any member contribution, with the exception of the requirements specified at [Licensing Commitments in W3C Submissions](https://www.w3.org/Consortium/Patent-Policy-20200915/#sec-submissions).

**Comment by michaelchampion** [comment]
The licensing commitment is another anachronistic feature of Member Submissions ... .
> must indicate whether or not each entity (Submitters and other licensors) will offer a license according to the [W3C RF licensing requirements](https://www.w3.org/Consortium/Patent-Policy-20200915/#def-RF) for any portion of the Member Submission that is subsequently incorporated in a [Patent Review Draft](https://www.w3.org/Consortium/Patent-Policy-20200915/#patent-review-draft) or [Recommendation](https://www.w3.org/Consortium/Process/#RecsW3C). The W3C Team may acknowledge the Member Submission if the answer to the licensing commitment is either affirmative or negative,

Why should W3C perpetuate process features that don't require RF patent commitments to contributions?

**Comment by palemieux** [comment]
@michaelchampion do other parts of the process or the patent policy cover the situation where a contribution is the result of the work of many outside of W3C?

**Comment by frivoal** [comment]
While member submissions aren't used terribly much, there are cases for which it isn't clear to me that there's a better replacement.

Say you have a file format, which is a de-facto standard without published documentation. As something that is already broadly used, unless there's a will to make a next version with more features, there's not much point in spinning up a WG (or even a CG) to discuss how it ought to be, that's already settled by usage. But it could still be convenient for the company that made it to share the documentation for that format, along with information of what patent regime it is under.

A member submission would seem to me to be a very appropriate way of sharing that. Members submissions aren't limited to this case, but they seem to me to be the only W3C process that's adequate for handling that sort of situation.

For instance, see this note from https://www.w3.org/TR/css-ui-3/#cursor:

> Note: At the time of writing this specification (spring 2015), the only file formats supported for cursors in common desktop browsers are the .ico and .cur file formats, as designed by Microsoft. For compatibility with legacy content, UAs are encouraged to support these, even though the lack of an open specification makes it impossible to have a normative requirement about these formats. Some information on these formats can be found [on Wikipedia](https://en.wikipedia.org/wiki/ICO_%28file_format%29).

I'd say that it would be a nice thing for Microsoft to release the documentation for these formats as a member submission, and it isn't entirely clear to me that any other W3C path to publication that would be suitable.

As for the patent regime, I'd surely prefer it to be RF, but what if, due to historical reasons on how the format was created, it cannot be? It might still be preferable to have documentation for the format and information about what patent regime it is under, than be left in the dark entirely.

It could still be true that the cost of having and maintaining this system exceeds any benefit it may have. I am not sure I have that strong an opinion about that yet.

**Comment by michaelchampion** [comment]
> But it could still be convenient for the company that made it to share the documentation for that format, along with information of what patent regime it is under.

Sure in 1995 or whenever the Process was defined, that might have been a valuable use case.  But In a world where GitHub, Microosft/Google docs in the cloud, very low cost web hosting solutions, etc. etc. etc. exist why should W3C invest in sharing *unvetted* documents with the world?  And if the answer is "submissions ARE vetted by the Director" then we have to address #639 and figure out how to get them authoritatively reviewed by someone else.  Is it worth it -- to the people maintaining the Process, those who will have to do the reviews, and the community trying to understand the Process --  for the various corner cases that Submissions once addressed  be supported in the future?  

> It could still be true that the cost of having and maintaining this system exceeds any benefit it may have. I am not sure I have that strong an opinion about that yet.

Right.  I don't have a strong opinion, but the complexity cost seems to outweigh any benefit I've heard in this thread and #639.

**Comment by frivoal** [comment]
> why should W3C invest in sharing unvetted documents with the world?

Possible reason: because these are about technologies upon which we have dependencies, whether we like it or not, and having them documented at a location which is guaranteed to be stable into the foreseeable future, along with a requirement for explicit documentation of patent licensing is preferable to having the same information hosted somewhere that might go 404 in 3 years, and for which there is no requirement of documenting the patent licensing.

All in all, I find marginal utility in the availability of member submissions. But they don't seem terribly important either.

**Comment by dwsinger** [comment]
Note that some sort of disclosure/publication process for specs that are relevant in the space is not completely unheard of. SMPTE has Registered Document Disclosure, for example; IETF has individual-track RFCs. 

Perhaps it would be _good_ to encourage more use of this, so relevant vendor specs that materially impact our field are published this way? I'm not keen on spending a lot of time on either promoting this vehicle nor shutting it down, right now, though.

**Comment by mnot** [comment]
The [Independent Submission Stream](https://www.rfc-editor.org/about/independent/) for RFCs isn't part of the IETF -- it's a separate stream with an editor (who is selected by the IAB).

That might get to the heart of why I'm wary of member submissions -- they have a smell of 'pay to publish' without any editorial oversight. In the past I've heard of them being used as an enticement to membership.

Right now, s 10 puts the decision to acknowledge in the hands of the Team without any guidance (beyond making sure the request is 'complete'). It might be better to put that decision in other hands, or at least to provide more guidance about what the purpose of member submissions are, and therefore what the criteria for their acceptance is.

**Comment by frivoal** [comment]
There has been [no member submission since 2020](https://www.w3.org/submissions/). I've changed my mind, and no longer think that this part of the Process justifies its continued existence based on some marginal benefit, even in a simplified form as proposed in https://github.com/w3c/w3process/issues/421.

It seems to me that it is in everyone's interest to keep the Process short enough that it is approachable to new comers (Member companies and individuals). As we grow various parts of it in response to new needs, we should also be willing to retire obsolete parts, lest we force anyone diligent enough to try and learn the process to read pages worth or irrelevant rules and concepts.

I think we should simply delete from the Process the entire [Member submission section](https://www.w3.org/Consortium/Process/Drafts/#Submission) and subsections. This would not prevent the Team for offering a "we'll host your document if it seems valuable" service and document it whereever they want (/Guide?), but I don't think keeping it as a right of members with formal processes around it is relevant anymore.

**Comment by nigelmegitt** [comment]
My sense is that the member submission process came out of a need, and even though that might be rarely used nowadays, I think the need probably does still exist. Before removing it, I think we need to understand what the expected model would be for a member to bring pre-existing work into W3C for use as the basis of a new Recommendation, and how issues like IPR would be handled. Perhaps there is a simpler alternative that does not require much, or any, spec text, but given that we don't have a proposal yet, I'd prefer to take no action, around the section as a whole.

One area that might incur maintenance costs now is the one about [rejection and appeals](https://www.w3.org/Consortium/Process/Drafts/#SubmissionNo) - I can imagine that refactoring that in terms of a Team Decision might simplify things a bit. I can't see a rationale for a whole separate Submission Appeals process now that we have Team Decision, assuming we can restrict visibility of such team decisions to the Team and the Submitter.

**Comment by frivoal** [comment]
> My sense is that the member submission process came out of a need

Yes, but that predates CGs. Now, that's a much more common way to bring work to W3C.

> how issues like IPR would be handled

Member submissions require you to disclose what your IPR is, but it doesn't require any favorable regime. Submitting something to a CG gives us more than that.

> I can imagine that refactoring that […]

Something like that used to be my preferred approach. I no longer think it's worth the effort.

> Before removing it

Note that I'm not necessarily saying we should discontinue the service. The Team could absolutely continue having this capability, and documenting how to submit things elsewhere (/Guide ?), which could be more focused on why you might want to do that, rather that the right and duties of various people. The Team provides IRC channels and all sorts of things without the being mandated by the Process. What removing it from the Process does is that it would no longer be a guaranteed right, letting us get rid of the even more unused appeals process, and no longer inflecting it on unsuspecting people.

**Comment by frivoal** [comment]
Note: closing this issue as proposed (with a removal of the Member submissions process) would also allow us to close: #639, #442, #421, #714.

**Comment by frivoal** [comment]
Removing Member Submissions was rejected in favor of simplifying them. See #412 and #936.
