### ISSUE TITLE
Who convenes Workshops?

### ISSUE THREAD

**Issue by mnot** [w3c/process#649]
First raised in #316.

The `director-free` branch of the process does not mention _who_ is able to / responsible for convening a workshop. Currently this is done by the Team. Some questions:

* [ ] Is it appropriate for the Team to make decisions about what topics we hold workshops on (and do not)? What accountability mechanism is in place, if so?
* [ ] Can the TAG (for example) request a Workshop, and if so can the Team refuse them?

There's a deeper issue here about strategic planning. While the Team has become more transparent about this over the years, its decision-making is currently only accountable to the Director.

**Comment by caribouW3** [comment]
Hi,
It is not quite true that it is the team's responsibility only. A number of workshops have in fact been initiated by other efforts like WGs, CGs, externally-funded projects, etc. and the team "just" helps with the organization.
I don't think it is desirable to list all the cases and restrict the ability to convene workshops. In fact I'm not even sure it's possible: People would certainly use another creative name for the same kind of meeting if they really want to have it.
The only thing that the process could do is to mandate to have a certain type of workshop before advancing to a certain step (e.g. group creation). I don't think we want to do that either.

**Comment by frivoal** [comment]
The actual constraints on Workshops and symposia are extremely limited:

> If a Workshop is being organized to address the pressing concerns of Members, the Team must issue the Call for Participation no later than six weeks prior to the Workshop’s scheduled start date. For other Workshops and Symposia, the Team must issue a Call for Participation no later than eight weeks prior to the meeting’s scheduled start date.

You could organize a meeting, call it a convention or a summit or a get-together, have be be identical in all ways to a Workshop, and the only difference would be that the above time constraint wouldn't apply. So if someone's serious about setting up a Workshop-or-equivalent, I don't think the Team can—or would try to—do much to stop them, and they might as well work together. Which I think they typically do. So in practice, I am not concerned.

I'm not against eventually developing a more fleshed out process for determining who can call workshops, what the criteria are, etc, but I don't think that at this point, I am not aware that this would be solving a real problem.

**Comment by jeffjaffe** [comment]
It is useful for folks to refer to our guidebook on the matter https://www.w3.org/Guide/meetings/workshops.html

**Comment by mnot** [comment]
Workshops can issue reports, and I don't think that any casual group of people can claim to issue a W3C Workshop Report. They get referenced, and carry some amount of weight presumably.

Even if we think that it's perfectly fine that the Team has control of when Workshops are convened (and it indeed might be so), the language in the Process is extremely passive -- just stating that they happen. This is the antithesis of accountability and transparency. At the very least, we should clarify who's responsible for convening them.

Alternatively, if we truly think that Workshops have no special status, why are they in the Process?

**Comment by TallTed** [comment]
(I have not drilled into current documentation on these; the following is based on my experience and reading of past docs when relevant at the time.)

Community Groups can also issue reports, which participants anticipate will be fed into Working Groups and/for other elements of the process.  CGs are expected to run for some time, with (I think) a year being on the low end, before producing such a report.  CGs are expected to operate mostly if not entirely remotely, via concalls, mailing lists, code repos, etc.  CGs are expected to have a fairly small focus area, though their output may have a ripple effect on many other groups.

Workshops, as I have understood them, are expected to run for a relatively few days of dense and intense face-to-face discussion, the result of which is anticipated to have significant effects, well beyond "ripples", on ongoing efforts by W3C and all its various participant groups.

-----

(@mnot — [_"This is the antithesis of accountability and transparency."_](https://github.com/w3c/w3process/issues/649#issuecomment-1261682483) This is rather incendiary language, and not the only recent instance of such from you, which I would not like directed at me when acting in good-faith as an author or other contributor to anything. I imagine that other contributors have similar feelings. Please modify your tone going forward.)

**Comment by plehegar** [comment]
There is a difference between a "Workshop" and a "W3C Workshop". The endorsement - or the non-endorsement - of W3C for a workshop is valuable information.

I don't think transparency is an issue here. Anyone is welcome to comment in the [strategy pipeline](https://github.com/w3c/strategy/issues?q=is%3Aissue+is%3Aopen+workshop). Just because it puts the burden on the community to pay attention doesn't make it less transparent.

A W3C Group also has a say when organizing a workshop in an area falling into their scope. Some Groups have organized workshops or meetups on their own in fact. It simply means that the event is organized by the W3C Group and not necessarily endorsed by W3C as a whole, which is fine.

I expect the Team to evaluate the value of a W3C workshop based on the W3C mission, principles, etc.

Leaving the workshop decision to the Team means that we should come up with the possibility to appeal the decision or formally object to such decision. Given the additional delays that this could add, I would recommend having an expedited way to deal with such appeal/FO. Workshops can take a long time to be organized and a late objection could jeopardize the effort significantly.

**Comment by dwsinger** [comment]
If we want to avoid a late FO, we can announce the intention/plan/hope to organize a workshop, and say explicitly: this is your chance to course-correct. If it's approved here, we will not later cancel or significantly change the nature of this Workshop.

**Comment by plehegar** [comment]
We could indeed introduce the idea of an advance notice, with leaving some flexibility on how advanced it has to be. For example, a workshop on "Banking Industry from the Web" was mentioned in 2019 but never got to the point of becoming concrete.

**Comment by mnot** [comment]
Right now the `director-free` branch [says](https://www.w3.org/Consortium/Process/Drafts/director-free/#GAEvents):

> The Team organizes Workshops and Symposia to promote early involvement in the development of W3C activities from Members and the public.

A clarification could add:

> Members and Groups (WGs, IGs, BGs, CGs, and the TAG) can suggest topics for Workshops to the Team; the status of suggested Workshops will be tracked using the [Strategic Funnel](https://github.com/w3c/strategy/issues?q=is%3Aissue+is%3Aopen+workshop).

---

Aside - later in the same section, it says:

> Organizers of the first type of Workshop may solicit position papers for the Workshop program and may use those papers to choose attendees and/or presenters.

... which is a little bit of a confusing use of _organizer_, since above the Team is identified as the organizer of a workshop. I think what happens is that the Team selects a PC, and the PC does the solicitation of papers, etc.

**Comment by mnot** [comment]
It might be useful to split this into two sub-issues:

1. Who can suggest a workshop? I think the uncontroversial answer is 'anyone' (approximately).
2. Who decides whether a workshop will happen? This is probably more contentious. Right now it seems to be de facto the Team, in that they can choose not to hold one through inaction.

**Comment by frivoal** [comment]
> Alternatively, if we truly think that Workshops have no special status, why are they in the Process?

I think the amount of things that the Process has to say about workshops has decreased enough that we could close this issue with no change.
