### ISSUE TITLE
Charter creation

### ISSUE THREAD

**Issue by mnot** [w3c/process#650]
The `director-free` branch currently says regarding charter development in 4.1:

> W3C creates charters for [chartered groups](https://www.w3.org/Consortium/Process/Drafts/director-free/#chartered-group) based on interest from the Members and Team.

That is very passive and indirect. **What part** of W3C does this -- Members? the TAG? The AB? The Team?  IIRC the intent was to empower _anyone_ to create a charter, but this language does not do that work.

First brought up in #316.

**Comment by plehegar** [comment]
I don't think we want to empower anyone to create a Charter. We need some filtering of what can be proposed to the AC. As a matter of fact, I hear concerns about our lack of process over what can be proposed as a Community Group. Similar to #653 , I'd expect AB/TAG/Team to collaborate on charter creation.

**Comment by mnot** [comment]
The answer doesn't need to be restrictive, necessarily -- it should just be definitive. E.g.,

> Any party (e.g., a Member, the TAG, the Team) can propose a charter to the Team. The Team will then...

**Comment by dwsinger** [comment]
is this different from #560 ?

**Comment by frivoal** [comment]
I think this has been answered by https://github.com/w3c/process/pull/851, and that we should close.

**Comment by fantasai** [comment]
(Closing per resolution](https://www.w3.org/2024/11/13-w3process-minutes.html).
