### ISSUE TITLE
Candidate Recommendation Draft vs "return to Working Draft"

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/process#726]
The Process document allows the [Director to send a document to a lower maturity level for further work](https://www.w3.org/2021/Process-20211102/#rec-track).

For a spec that has reached CR (not requested to move to PR), [returning to WD]((https://www.w3.org/2021/Process-20211102/#transition-cr)) can presumably only happen when the WG requests to update the CR Snapshot. But I'm not clear under what conditions the Director would do that when "further work" can now happen through Candidate Recommendation drafts. In both cases, a CR Snapshot would be the required next stage.

Comparing the requirements between [transition from WD to CR](https://www.w3.org/Guide/transitions?profile=CR&cr=new#transition-reqs) and [transition to update a CR Snapshot](https://www.w3.org/Guide/transitions?profile=CR&cr=snapshot#update-reqs), a re-transition from WD to CR would add the following requirements compared to a CRD → CRS update:
* a full transition cannot use Streamlined Publication Approval (although it is strict enough that it doesn't seem lighter than a full transition)
* the full transition requires documenting changes to dependencies "in the development of specification"
* the full transition requires documenting how [adequate implementation experience](https://www.w3.org/2021/Process-20211102/#adequate-implementation) will be demonstrated,
* the update process requires demonstration of wide review only on changes, when the full transition requires it on the whole document.

So is the goal that the Director would send back a document in the follow circumstances:
* to force a Director review of changes in dependencies prior to the PR transition (I'm not sure how that would occur and how it would be useful though),
* to force a Director review of the CR exit criteria ("implementation experience")
* to force a full wide review of the document (vs only on changes since the last CR Snapshot)
?

Or is the CRS→WD path mostly a left over from the previous process?

**Comment by frivoal** [comment]
In the (newer) Director-free Process, https://www.w3.org/policies/process/drafts/#rec-track-regression now says:

> Additionally, with the approvals (by group decision) of each of the TAG and the AB the Team may return the technical report to a lower maturity stage in response to wide review or a formal objection.

I think this resolves the issue as stated, as it is now clear both how it happens and why it may happen.

**Comment by plehegar** [comment]
Unless there is new information by December 20, this issue will get closed.
