### ISSUE TITLE
The sentence about affiliation change causing a seat to be vacated is in the wrong place

### ISSUE THREAD

**Issue by dwsinger** [w3c/process#770]
This

> If a participant changes affiliation, but the [participation constraints](https://www.w3.org/2023/Process-20230612/#AB-TAG-constraints) are met, that participant’s seat becomes vacant at the next regularly scheduled election for that group.

is in [3.3.3.6](https://www.w3.org/2023/Process-20230612/#AB-TAG-vacated), which talks about vacancy management. It should be in [3.3.3.2](https://www.w3.org/2023/Process-20230612/#AB-TAG-constraints), which is where the constraints are established.

Note that this list:

> An [Advisory Board](https://www.w3.org/2023/Process-20230612/#advisory-board) or [TAG](https://www.w3.org/2023/Process-20230612/#technical-architecture-group) participant’s seat is vacated when:
> 
> - the participant resigns, or
> - an Advisory Board or TAG participant changes affiliations such that the [Advisory Board and TAG participation constraints](https://www.w3.org/2023/Process-20230612/#AB-TAG-constraints) are no longer met, or
> - the [CEO](https://www.w3.org/2023/Process-20230612/#ceo) dismisses the participant for failing to meet the criteria in section [§ 3.1.1 Individual Participation Criteria](https://www.w3.org/2023/Process-20230612/#ParticipationCriteria), or
> - their term ends.

doesn't include "at the next election after an affiliation change", but if we were to move it into the constraints, the second bullet would apply.

**Comment by fantasai** [comment]
AFAICT the sentence in question does belong where it is: it's not imposing a participation constraint (which the "no two participants with the same primary affiliation" rules in 3.3.3.2 do), but triggers vacation of a seat when there's *any* change in affiliation, even one that doesn't violate any constraints -- and so belongs together with the other reasons why a seat might be vacated (in 3.3.3.6).

Closing with no change, by editor discretion.
