### ISSUE TITLE
Are TAG Appointments mandatory for the Team to fill?

### ISSUE THREAD

**Issue by martinthomson** [w3c/process#811]
In #810, it seems like there is some lack of clarity about whether the Team is *required* to appoint TAG members or whether they are simply given the option of doing so (and maybe encouraged to do it).

(Most of the text below is from [this section](https://www.w3.org/2023/Process-20231103/#TAG-appointments) of the current process document.)

The case for a mandatory appointment is made implicitly, with statements like [this one](https://www.w3.org/2023/Process-20231103/#tag-participation):

> The [TAG](https://www.w3.org/2023/Process-20231103/#technical-architecture-group) consists of *[...]* Three participants [appointed by the Team](https://www.w3.org/2023/Process-20231103/#TAG-appointments);

And

> The [Team](https://www.w3.org/2023/Process-20231103/#team) is responsible for appointing 3 of the participants to the [Technical Architecture Group](https://www.w3.org/2023/Process-20231103/#technical-architecture-group).

And this one in [this later section](https://www.w3.org/2023/Process-20231103/#AB-TAG-vacated):

> When an appointed [TAG](https://www.w3.org/2023/Process-20231103/#technical-architecture-group) seat is vacated, the [Team](https://www.w3.org/2023/Process-20231103/#team) [appoints](https://www.w3.org/2023/Process-20231103/#TAG-appointments) a replacement.

That all seems unequivocal, if not a direct requirement, but then there are statements like:

> The [Team](https://www.w3.org/2023/Process-20231103/#team) should actively seek candidates for appointment to the TAG, *[...]*

And maybe even subtle nods like:

> The [Team](https://www.w3.org/2023/Process-20231103/#team)'s choice of appointee(s)

Though that last one might just be in recognition of the staggered nature of appointments, noting that some years the Team will only have a single appointment to make.

**Comment by indianfako** [comment]
> In #810, it seems like there is some lack of clarity about whether the Team is *required* to appoint TAG members or whether they are simply given the option of doing so (and maybe encouraged to do it).
> 
> (Most of the text below is from [this section](https://www.w3.org/2023/Process-20231103/#TAG-appointments) of the current process document.)
> 
> The case for a mandatory appointment is made implicitly, with statements like [this one](https://www.w3.org/2023/Process-20231103/#tag-participation):
> 
> > The [TAG](https://www.w3.org/2023/Process-20231103/#technical-architecture-group) consists of *[...]* Three participants [appointed by the Team](https://www.w3.org/2023/Process-20231103/#TAG-appointments);
> 
> And
> 
> > The [Team](https://www.w3.org/2023/Process-20231103/#team) is responsible for appointing 3 of the participants to the [Technical Architecture Group](https://www.w3.org/2023/Process-20231103/#technical-architecture-group).
> 
> And this one in [this later section](https://www.w3.org/2023/Process-20231103/#AB-TAG-vacated):
> 
> > When an appointed [TAG](https://www.w3.org/2023/Process-20231103/#technical-architecture-group) seat is vacated, the [Team](https://www.w3.org/2023/Process-20231103/#team) [appoints](https://www.w3.org/2023/Process-20231103/#TAG-appointments) a replacement.
> 
> That all seems unequivocal, if not a direct requirement, but then there are statements like:
> 
> > The [Team](https://www.w3.org/2023/Process-20231103/#team) should actively seek candidates for appointment to the TAG, *[...]*
> 
> And maybe even subtle nods like:
> 
> > The [Team](https://www.w3.org/2023/Process-20231103/#team)'s choice of appointee(s)
> 
> Though that last one might just be in recognition of the staggered nature of appointments, noting that some years the Team will only have a single appointment to make.

**Comment by indianfako** [comment]
> In #810, it seems like there is some lack of clarity about whether the Team is *required* to appoint TAG members or whether they are simply given the option of doing so (and maybe encouraged to do it).
> 
> (Most of the text below is from [this section](https://www.w3.org/2023/Process-20231103/#TAG-appointments) of the current process document.)
> 
> The case for a mandatory appointment is made implicitly, with statements like [this one](https://www.w3.org/2023/Process-20231103/#tag-participation):
> 
> > The [TAG](https://www.w3.org/2023/Process-20231103/#technical-architecture-group) consists of *[...]* Three participants [appointed by the Team](https://www.w3.org/2023/Process-20231103/#TAG-appointments);
> 
> And
> 
> > The [Team](https://www.w3.org/2023/Process-20231103/#team) is responsible for appointing 3 of the participants to the [Technical Architecture Group](https://www.w3.org/2023/Process-20231103/#technical-architecture-group).
> 
> And this one in [this later section](https://www.w3.org/2023/Process-20231103/#AB-TAG-vacated):
> 
> > When an appointed [TAG](https://www.w3.org/2023/Process-20231103/#technical-architecture-group) seat is vacated, the [Team](https://www.w3.org/2023/Process-20231103/#team) [appoints](https://www.w3.org/2023/Process-20231103/#TAG-appointments) a replacement.
> 
> That all seems unequivocal, if not a direct requirement, but then there are statements like:
> 
> > The [Team](https://www.w3.org/2023/Process-20231103/#team) should actively seek candidates for appointment to the TAG, *[...]*
> 
> And maybe even subtle nods like:
> 
> > The [Team](https://www.w3.org/2023/Process-20231103/#team)'s choice of appointee(s)
> 
> Though that last one might just be in recognition of the staggered nature of appointments, noting that some years the Team will only have a single appointment to make.

**Comment by fantasai** [comment]
My understanding of the Process is that is mandatory to appoint, and the phrasing supports this as you note. Regarding the ones you're unsure of:

> The [Team](https://www.w3.org/2023/Process-20231103/#team) should actively seek candidates for appointment to the TAG

This recommendation is about the Team actively looking for candidates, not just passively taking nominations.

 > The [Team](https://www.w3.org/2023/Process-20231103/#team)'s choice of appointee(s)
 
 As you note, this optional pluralization is about the staggered number of appointees; not about whether the Team gets to choose how many.

**Comment by plehegar** [comment]
Unless there is new information by December 20, this issue will get closed.
