### ISSUE TITLE
Strip section 6.2.2.1 “wide review” of the mailing list currently mentioned

### ISSUE THREAD

**Issue by koalie** [w3c/process#815]
Hello,

The Team (me, @swickr and @plehegar) has flagged that the Process Document refers to 1 (one) mailing list in an example. 
It's in section [6.2.2.1. "wide review"](https://www.w3.org/2023/Process-20231103/#wide-review).

Instead of augmenting the process document with references to all the mailing lists that are used as part of executing the process document, we think it makes more sense to remove the example in parenthetical.

Performing such a change makes the Process and the way the Team implements it independent (which is desirable) and removes the possible perception that only one mailing list is used.

Thank you!

**Comment by frivoal** [comment]
See https://github.com/w3c/process/pull/952
