### ISSUE TITLE
Visibility of FO handling

### ISSUE THREAD

**Issue by frivoal** [w3c/process#870]
Forking a new issue from a comment by @tantek in https://github.com/w3c/w3process/issues/852#issuecomment-2115069957:

> One key addition I would like to see added, for the reasons of documenting a proper process and acknowledgement of how Formal Objections were handled:
> 
> IF the Team recommends a path which is equivalent to DROPPING the (i.e. REJECTING) the proposed action that the AC voted on, e.g.
> 
> * If the AC voted on a charter, and the Team withdraws the charter that was voted on
> * if the AC voted on a REC transition, and the Team withdraws the version of the REC that was voted on (for any reason, with any variations)
> 
> THEN the council as part of accepting the Team's recommendation MUST record for the matter of historical record, something like:
> 
> > One or more Formal Objections to AC poll (insert permalink to AC poll) were UPHELD and thus the item that was polled is recorded as REJECTED by W3C.
> 
> This will help make it clear:
> 
> * what happened with so-and-so formal objection?
> * which formal objections were UPHELD (perhaps as a set) and which were DISMISSED (perhaps as a set)?
> 
> which we may use to gather statistics etc. in the future on things like:
> 
> * number of W3C polls which were REJECTED or PASSED
> * specifically, number of proposed charters which were REJECTED or PASSED
> * number of proposed REC transitions which were REJECTED or PASSED etc.
> 
> and then we can use the REJECTED examples to document the WHYs of REJECTION to help improve future proposals to poll, and polls themselves.

**Comment by frivoal** [comment]
Basically, I'm flexible on how we get there, but I support the principle that no FO should be followed by silence. Doesn't matter if it's overruled or sustained, doesn't matter if it's short circuit or delegation or whatever, if there is an FO, we must let people know how it was disposed.

Some of this may already exist through various existing Process rules, but we may have holes to plug or other improvements to make. Let's look into it and fix whatever is missing.

**Comment by hober** [comment]
It's not clear to me that UPHELD is the correct state to record in the situation @tantek describes. The FO has been made moot, as the decision that was objected to has been un-made. It would be clearest to record that the FO was made moot.

**Comment by frivoal** [comment]
I the “[…] and the Team withdraws the charter” scenario, I agree that's not FOs being upheld, but being rendered moot. The broader point which I believe is right is that once an FO has been made, interested parties need to be able to figure out what has happened to it. That might take different paths depending on what has happened to it, but that should be discoverable, without excessively complicated research.

**Comment by frivoal** [comment]
Partly related to https://github.com/w3c/strategy/issues/475
