### ISSUE TITLE
repo name nit: it'd be nice if this were simply w3c/process

### ISSUE THREAD

**Issue by hober** [w3c/process#871]

**Comment by frivoal** [comment]
Sure. Does github.io do redirects if we rename the repo, or would we break a bunch of links?

**Comment by plehegar** [comment]
There is a [way to do the redirect](https://w3c.github.io/repo-transfer.html). We'll need to add a file in [w3c.github.io](https://github.com/w3c/w3c.github.io).

**Comment by frivoal** [comment]
> There is a [way to do the redirect](https://w3c.github.io/repo-transfer.html).

That link seems to be about something else: moving a repo from one org to another. Here, it's already in the right org, it just needs a name change. I _think_ the redirects work automatically in that case, but I would like to be sure.

**Comment by plehegar** [comment]
> > There is a [way to do the redirect](https://w3c.github.io/repo-transfer.html).
> 
> That link seems to be about something else: moving a repo from one org to another. Here, it's already in the right org, it just needs a name change. I _think_ the redirects work automatically in that case, but I would like to be sure.

I'm pretty confident that it will work but I'll double check nevertheless.

**Comment by plehegar** [comment]
ok. Renaming done. w3c.github.io are redirected.
W3C Proxy still needs to be updated to use directly w3c.github.io/process

**Comment by frivoal** [comment]
currently it looks like https://www.w3.org/Consortium/Process/Drafts/ is redirecting to github.io instead of proxying it. Or maybe it's proxying the old github.io address, and that is loading something that redirects to the new one

**Comment by frivoal** [comment]
PSA: a side effect I forgot to foresee: I needed to update my email filters, as github notifications are now sent via the `<process.w3c.github.com>` mailinst list instead of `<w3process.w3c.github.com>`.

**Comment by vivienlacourba** [comment]
> currently it looks like https://www.w3.org/Consortium/Process/Drafts/ is redirecting to github.io instead of proxying it. Or maybe it's proxying the old github.io address, and that is loading something that redirects to the new one

@frivoal this will be taken care of at the same time as we introduce the new Process document URI per issue #729.

**Comment by plehegar** [comment]
Everything should be fine due to the renaming. #729 will be dealt with separately.
