### ISSUE TITLE
Phrasing disagreement

### ISSUE THREAD

**Issue by frivoal** [w3c/process#899]
In https://github.com/w3c/process/pull/878/files#r1623157565, @TallTed commented he thought that the following phrasing was not appropriate/grammatical:

> For Recommendations explicitly identified as allowing new features, tentative new features **may be annotated in as candidate additions** […]

The "in as" sequence in "annotated in as candidate additions" is what bothers him, and proposed solutions have been either to delete the "in" or to replace it with "therein".

I am not opposed to switching to some alternative phrasing if it makes everyone happy, but I disagree that the current phrasing is problematic. "in as" may not be a valid preposition in and of its own, but it's not trying to be one here. "in" is grouped with the preceding verb, and "as" is grouped with the following noun phrase. I see this as a phrasal verb, not different from things like:
* "Use `sudo` to log in as root."
* "The hotel clerk sayd: she checked in as a guest yesterday evening"
* "Despite the difficulty of the task, they dived in as enthusiastically as if it had been a game"
* "Halfway through the game, he joined in as quarterback."
* "Your pitch is convincing. Count me in as an investor.

As the examples show above, the sequence "verb + in" followed by "as + phrase" can be perfectly valid.

Here, I want to use "annotate in" rather than just "annotate" to convey the following nuance:
* "to annotate a new feature" would mean "to put an annotation onto a feature".
* "to annotate in a new feature" means "to put a new feature (into the document) as an annotation".

So I think the original phrasing is fine, and removing the "in" would be wrong

We _could_ switch to "therein", but it seems just as unnecessary heavy sounding, as in the following example:
> To unsubscribe from this newsletter, visit our website, log therein, and change your settings.

You *could* say that, but the following phrasing is a lot more natural
> To unsubscribe from this newsletter, visit our website, log in, and change your settings.

**Comment by chrisn** [comment]
I agree with you both: "annotated in" is the right concept, but "may be annotated in as candidate additions" reads awkwardly. How about hyphenating, i.e., "may be annotated-in as candidate additions" ?

**Comment by chaals** [comment]
"annotated in" in the way you are proposign to use it, @frivoal, doesn't read naturally to an english speaker.

The actual pattern you are describing is specific to certain verbs, which take on a particular meaning when associated with a given preposition. You can dial someone in, but you ring someone up, and you call them. It's not a generalised structure. I agree with @TallTed that the phrasing you are proposing is wrong, and you should use something like "add to a document as an annotation".

(You're right about the impact of removing the "in" from the sentence, FWIW).

**Comment by nigelmegitt** [comment]
I think the problem is the use of "annotate in" - my Oxford English Dictionary says the verb "annotate" is transitive, and I _think_ that means that it takes an object directly, as opposed to an intransitive verb like "look" which only takes one indirectly. For example, you can "look in the cup" but you cannot "look the cup", whereas you can "annotate an entry" but you cannot "annotate in an entry". Some verbs can be used both transitively and intransitively, but "annotate" is not one of those.

If this grammatical analysis is correct, one fix would be to remove the word "in" and use "... may be annotated as candidate additions".

**Comment by dwsinger** [comment]
yes, while "check in" is a phrasal verb, "annotated in" is not. so it reads weirdly. re-phrasing is probably best. something like

> tentative new features may be added as candidate additions in annotations […]
