### ISSUE TITLE
Invited Experts without Member-only access

### ISSUE THREAD

**Issue by jyasskin** [w3c/process#900]
https://www.w3.org/invited-experts/#memaccess says that
> At the discretion of the Team Contact, or at the request of the invited expert themselves, W3C Member access may not be granted. This option accounts for the Invited Experts who do not wish to be responsible for managing member-confidential information, or are unable to.
> 
> Additionally, on a case by case basis, a group may define in its charter that invitations to invited experts will not include W3C Member access.

And the [PING charter](https://www.w3.org/2019/09/privacy-ig-charter.html#participation) and [draft SING charter](https://w3c.github.io/charter-drafts/2024/ig-security.html#participation) do so define.

However, I can't find wording in the Process to support this. The only statement I see is

> “Member-only” information is available to authorized parties only, including representatives of Member organizations, [Invited Experts](https://www.w3.org/policies/process/#invited-expert-wg), ...

Am I missing something, should the Process endorse the existence of Invited Experts without Member-only access, or should the charters stop claiming that they don't grant Member-only access?

**Comment by chrisn** [comment]
> should the Process endorse the existence of Invited Experts without Member-only access

I do support the existence, as we want to groups like SING to have more open participation (as we do with CGs), but without necessarily giving member access, which could lead to members reconsidering the value of membership.

Some clarification of [public participants](https://www.w3.org/policies/process/drafts/#public-participant-ig) in IGs could be useful. For example, does subscribing to the mailing list enable anyone to join IG meetings or contribute to IG reports? If not, it seems like the criteria in section [3.4.3.3](https://www.w3.org/policies/process/drafts/#invited-expert-wg), referenced from [3.4.3.4](https://www.w3.org/policies/process/drafts/#invited-expert-ig) are needed for IG participants.

Also, mailing lists are becoming less commonly used now as groups tend to prefer GitHub issues, so I'm not sure this is a good criteria any more. And WGs also have mailing lists, so what distinction is being made between IGs and WGs there? Is someone who subscribes and posts go a WG mailing list not a public participant to a WG?

**Comment by chrisn** [comment]
I'd suggest not saying "most", so:

> “Member-only” information is available to authorized parties only, including representatives of Member organizations, [Invited Experts](https://www.w3.org/policies/process/#invited-expert-wg) (as described in https://www.w3.org/invited-experts/#memaccess), ...
