### ISSUE TITLE
Typical group duration is not six months to two years

### ISSUE THREAD

**Issue by svgeesus** [w3c/process#918]
In **4.3. Content of a Charter** we [find](https://www.w3.org/policies/process/drafts/#WGCharter)

> The duration of the group (typically from six months to two years). 

A [venerable](https://www.w3.org/2017/Process-20170301/#WGCharter) but wildly inaccurate phrase, which should be corrected.

Let us imagine a WG has been chartered to develop a Rec-track document whose contents are

> _This specification intentionally left blank_

and thus, that there is zero technical discussion.

Let us also imagine the charter start date is 1 Jan 2025, that there are no holiday periods, and the cfc for FPWD is on Weds 1 Jan 2025. The [milestone calculator](https://w3c.github.io/spec-releases/milestones/?fpwd=2025-01-21), assuming the FPWD transition request is instantly approved, tells us that the  FPWD is published Tuesday, January 21 2025, triggering the 150 day exclusion period.

In this alternate reality, wide review of the content-free draft takes just one day.

The calculator tells us that the Recommendation is published on Tuesday, August 5 2025 and, as there is no content there is no need for maintenance and the group can be closed, around 8 months after it started.

The problem is that the mythical six-month charter was 1 Jan 2025 to 1 July 2025, so some time in May-June the group got a 3 month extension to enable it to continue it's work.

So a six month group duration is not just _atypical_ but actually _impossible_.

I didn't take the time to calculate the duration of all WGs to date, but am fairly confident that 2 years is not a typical duration either.

I think the actual problem is that two concepts are being conflated:

1. The duration the group requires to bring some work to a successful conclusion
2. The duration the AC is comfortable approving, before taking another look at how the group is doing.

My suggested fix is therefore

**The duration of the proposed charter for the group (typically two years, although shorter periods may be appropriate for re-chartering an existing group to finish up some work).**

**Comment by cwilso** [comment]
Strong agreement with the suggested fix.
